In [ ]:
# mengimport library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# metode svm
from sklearn import svm, datasets
from sklearn.model_selection import train_test_split

In [ ]:
#mengimport dataset (dataset yang digunakan yaitu dataset redwine)
data = pd.read_csv('/content/sample_data/winequality-red.csv')
data.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [ ]:
# proses splint data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=1
)

In [ ]:
from sklearn import svm
model_SVM = svm.SVC(kernel='linear')
model_SVM.fit(x_train, y_train)
y_predict = model_SVM.predict(x_test) # berisi hasil data testing

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
#testing
prediksi = model_SVM.predict([[0.70, 0.00, 1.9, 0.76, 1.0]]) # angkanya bebas
if prediksi == "0":
  print(prediksi, "kualitas red wine rendah")
else:
  print(prediksi, "kualitas red wine tinggi")

[5] kualitas red wine tinggi


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
# menghitung confusion matrix
from sklearn.metrics import  confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_predict)
print(confusion_matrix)

[[  0   0   1   0   0   0]
 [  0   0   7   3   0   0]
 [  0   0 102  41   0   0]
 [  0   0  50  79   0   0]
 [  0   0   6  29   0   0]
 [  0   0   1   1   0   0]]


In [ ]:
# menampilkan report hasil confusion matrix
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predict)) 

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00        10
           5       0.61      0.71      0.66       143
           6       0.52      0.61      0.56       129
           7       0.00      0.00      0.00        35
           8       0.00      0.00      0.00         2

    accuracy                           0.57       320
   macro avg       0.19      0.22      0.20       320
weighted avg       0.48      0.57      0.52       320



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# New Section

In [ ]:
#pembagian Atribut Independen (x) dan Atribut Dependen (y)
x = pd.DataFrame(data.iloc[:,1:6])
y = pd.DataFrame(data.iloc[:,11:12])

In [ ]:
print("5 paling atas data fitur: \n" , x.head())
print("=========================")
print("5 paling atas data kelas: \n" , y.head())

5 paling atas data fitur: 
    volatile acidity  citric acid  ...  chlorides  free sulfur dioxide
0              0.70         0.00  ...      0.076                 11.0
1              0.88         0.00  ...      0.098                 25.0
2              0.76         0.04  ...      0.092                 15.0
3              0.28         0.56  ...      0.075                 17.0
4              0.70         0.00  ...      0.076                 11.0

[5 rows x 5 columns]
5 paling atas data kelas: 
    quality
0        5
1        5
2        5
3        6
4        5
